import { describe, expect, it } from "vitest";
import { InvestigationModel } from "../../src/server/InvestigationModel.js";
import type {
  BuildManifest,
  BuildModule,
  BuildSnapshot,
  CoverageReport,
  SourceFileReport,
  UsageMetrics,
} from "../../src/shared/types.js";

function metrics(input: Partial<UsageMetrics> = {}): UsageMetrics {
  return {
    emittedBytes: 0,
    loadedBytes: 0,
    executedBytes: 0,
    unusedBytes: 0,
    notLoadedBytes: 0,
    mappedBytes: 0,
    unmappedBytes: 0,
    usageRatio: null,
    ...input,
  };
}

function manifest(): BuildManifest {
  return {
    hash: "build",
    mode: "production",
    context: "/project",
    publicPath: "/",
    builtAt: 1,
    assets: [],
    chunks: [],
    modules: [
      {
        id: "consumer",
        identifier: "/project/src/consumer.js",
        readableIdentifier: "./src/consumer.js",
        name: "./src/consumer.js",
        resource: "/project/src/consumer.js",
        moduleType: "javascript/auto",
        chunks: [],
        issuer: null,
        entry: true,
        size: 20,
        usedExports: true,
        providedExports: null,
        optimizationBailout: [],
        nested: false,
      },
      {
        id: "target",
        identifier: "/project/src/target.js",
        readableIdentifier: "./src/target.js",
        name: "./src/target.js",
        resource: "/project/src/target.js",
        moduleType: "javascript/auto",
        chunks: [],
        issuer: "./src/consumer.js",
        entry: false,
        size: 20,
        usedExports: ["value"],
        providedExports: ["value"],
        optimizationBailout: [],
        nested: false,
      },
    ],
    entrypoints: [],
    diagnostics: [],
    capabilities: {
      usedExports: "enabled",
      sourceMap: "full",
      originalLocations: "exact",
    },
    counts: {
      assets: 0,
      javascriptAssets: 0,
      chunks: 0,
      modules: 2,
      sourceMaps: 0,
      references: 1,
      codeGenerationSources: 1,
    },
    previewAvailable: false,
    publicPathSupported: true,
  };
}

function source(
  id: string,
  moduleId: string,
  content: string,
  state: "executed" | "not-executed" = "executed",
): SourceFileReport {
  return {
    id,
    path: id,
    displayPath: id,
    category: "first-party",
    metrics: metrics({
      emittedBytes: 10,
      loadedBytes: 10,
      executedBytes: state === "executed" ? 10 : 0,
      unusedBytes: state === "executed" ? 0 : 10,
      mappedBytes: 10,
      usageRatio: state === "executed" ? 1 : 0,
    }),
    chunks: [],
    loadedChunks: [],
    moduleIds: [moduleId],
    duplicated: false,
    content,
    lines: [
      {
        line: 1,
        text: content,
        buildState: "retained",
        runtimeState: state,
        emittedBytes: 10,
        loadedBytes: 10,
        executedBytes: state === "executed" ? 10 : 0,
        chunks: [],
        ranges: [{ startColumn: 0, endColumn: content.length, executed: state === "executed" }],
      },
    ],
  };
}

function report(files: SourceFileReport[]): CoverageReport {
  return {
    version: 2,
    buildHash: "build",
    createdAt: 1,
    metrics: metrics(),
    moduleMetrics: metrics(),
    importSummary: {
      importedEntries: 1,
      matchedAssets: 1,
      ignoredEntries: [],
      precision: "per-block",
    },
    tree: {
      id: "root",
      name: "Sources",
      path: "",
      kind: "root",
      category: "all",
      metrics: metrics(),
      chunks: [],
      duplicated: false,
      children: [],
    },
    files,
    chunks: [],
    opportunities: [],
  };
}

function snapshot(files: SourceFileReport[]): BuildSnapshot {
  return {
    manifest: manifest(),
    assets: new Map(),
    maps: new Map(),
    originalSources: new Map(
      files.flatMap((file) => (file.content ? [[file.path, file.content]] : [])),
    ),
    exportGraph: { modules: [], edges: [], sourceToModuleIds: {} },
    references: [
      {
        id: "edge",
        originId: "consumer",
        targetId: "target",
        dependencyType: "esm import",
        request: "./target.js",
        exports: ["value"],
        active: true,
        location: {
          start: { line: 1, column: 9 },
          end: { line: 1, column: 14 },
        },
      },
    ],
    codeGeneration: new Map([
      [
        "target",
        [
          {
            moduleId: "target",
            runtimes: [[]],
            content: "const value = 1;",
            map: null,
            mapError: "missing map",
          },
        ],
      ],
    ]),
    outputPath: "/project/dist",
    indexAsset: null,
  };
}

describe("InvestigationModel", () => {
  it("falls back to module code generation when mapped generated bytes are zero", () => {
    const target = source("src/target.js", "target", "export const value = 1;");
    target.metrics = metrics();
    const targetLine = target.lines[0];
    if (!targetLine) throw new Error("Missing target source line");
    target.lines[0] = {
      ...targetLine,
      buildState: "unknown",
      runtimeState: "not-loaded",
      emittedBytes: 0,
      executedBytes: 0,
      ranges: [],
    };
    const model = new InvestigationModel(snapshot([target]), report([target]), new Map());

    expect(model.module("target")?.views).toMatchObject({
      source: true,
      output: true,
      hasMappedOutput: false,
      preferred: "output",
      outputKind: "module-code-generation",
    });
    expect(model.code("target", "output", null)).toMatchObject({
      content: "const value = 1;",
      provenance: "module-code-generation",
      spans: [{ start: 0, end: 16, status: "unknown" }],
    });
  });

  it("paginates references, finds the shortest entry path, and returns covered usage code", () => {
    const consumer = source("src/consumer.js", "consumer", 'import { value } from "./target.js";');
    const target = source("src/target.js", "target", "export const value = 1;");
    const model = new InvestigationModel(
      snapshot([consumer, target]),
      report([consumer, target]),
      new Map(),
    );

    const references = model.references("target", "in", 0, 1);
    expect(references?.total).toBe(1);
    expect(references?.counts).toEqual({ in: 1, out: 0, both: 1 });
    expect(references?.entryPath.map((module) => module.id)).toEqual(["target", "consumer"]);
    const snippet = model.snippet("edge");
    expect(snippet).toMatchObject({
      available: true,
      filename: "src/consumer.js",
      highlight: { coverageStatus: "executed" },
      code: {
        content: 'import { value } from "./target.js";',
        spans: [{ status: "executed" }],
        hasPrevious: false,
        hasNext: false,
      },
    });
    expect(snippet?.code?.content.slice(snippet.highlight?.start, snippet.highlight?.end)).toBe(
      "value",
    );
  });

  it("builds a bounded transitive module graph instead of stopping at direct references", () => {
    const target = source("src/target.js", "target", "export const value = 1;");
    const consumer = source("src/consumer.js", "consumer", 'import { value } from "./target.js";');
    const captured = snapshot([consumer, target]);
    const base = captured.manifest.modules[0] as BuildModule;
    const upstream: BuildModule = {
      ...base,
      id: "upstream",
      identifier: "/project/src/upstream.js",
      readableIdentifier: "./src/upstream.js",
      name: "./src/upstream.js",
      resource: "/project/src/upstream.js",
      entry: false,
    };
    const entry: BuildModule = {
      ...base,
      id: "entry",
      identifier: "/project/src/entry.js",
      readableIdentifier: "./src/entry.js",
      name: "./src/entry.js",
      resource: "/project/src/entry.js",
      entry: true,
    };
    captured.manifest.modules.push(upstream, entry);
    captured.references.push(
      {
        id: "consumer-upstream",
        originId: "upstream",
        targetId: "consumer",
        dependencyType: "esm import",
        request: "./consumer.js",
        exports: ["render"],
        active: true,
        location: null,
      },
      {
        id: "entry-upstream",
        originId: "entry",
        targetId: "upstream",
        dependencyType: "esm import",
        request: "./upstream.js",
        exports: ["start"],
        active: true,
        location: null,
      },
    );
    const model = new InvestigationModel(captured, report([consumer, target]), new Map());

    const graph = model.references("target", "in", 0, 80, 2)?.graph;
    expect(graph?.nodes.map(({ module, depth }) => [module.id, depth])).toEqual([
      ["target", 0],
      ["consumer", -1],
      ["upstream", -2],
    ]);
    expect(graph?.edges.map((edge) => [edge.originId, edge.targetId])).toEqual([
      ["consumer", "target"],
      ["upstream", "consumer"],
    ]);
    expect(graph).toMatchObject({
      requestedDepth: 2,
      reachedDepth: 2,
      truncated: true,
      truncation: { depth: true, nodes: false, edges: false, perModule: false },
    });

    const both = model.references("consumer", "both", 0, 80, 2)?.graph;
    expect(
      both?.nodes
        .map(({ module, depth }) => [module.id, depth] as const)
        .sort(([left], [right]) => left.localeCompare(right)),
    ).toEqual([
      ["consumer", 0],
      ["entry", -2],
      ["target", 1],
      ["upstream", -1],
    ]);
    expect(both?.truncated).toBe(false);
  });

  it("walks importer export names through the bounded reference graph", () => {
    const target = {
      ...(manifest().modules.find((module) => module.id === "target") as BuildModule),
      name: "./app-config.js",
      resource: "/project/app-config.js",
      usedExports: ["createWebAppConfigImpl"],
      providedExports: ["createWebAppConfigImpl"],
    };
    const suite: BuildModule = {
      ...target,
      id: "suite",
      identifier: "/project/suite.js",
      name: "./suite.js",
      resource: "/project/suite.js",
      usedExports: ["createWebSuite"],
      providedExports: ["createWebSuite"],
    };
    const barrel: BuildModule = {
      ...suite,
      id: "barrel",
      identifier: "/project/index.js",
      name: "./index.js",
      resource: "/project/index.js",
    };
    const entry: BuildModule = {
      ...suite,
      id: "entry",
      identifier: "/project/entry.js",
      name: "./entry.js",
      resource: "/project/entry.js",
      entry: true,
      usedExports: true,
      providedExports: null,
    };
    const build = snapshot([]);
    build.manifest.modules = [target, suite, barrel, entry];
    build.originalSources = new Map([
      ["app-config.js", "export function createWebAppConfigImpl() {}"],
      [
        "suite.js",
        'import { createWebAppConfigImpl } from "./app-config.js"; export function createWebSuite() { return createWebAppConfigImpl(); }',
      ],
      ["index.js", 'export { createWebSuite } from "./suite.js";'],
      ["entry.js", 'import { createWebSuite } from "./index.js"; createWebSuite();'],
    ]);
    const edge = (
      id: string,
      originId: string,
      targetId: string,
      exports: string[] | null,
      active = true,
      request = "./dependency.js",
    ) => ({
      id,
      originId,
      targetId,
      dependencyType: "esm import specifier",
      request,
      exports,
      active,
      location: null,
    });
    build.references = [
      edge(
        "suite-app-config",
        "suite",
        "target",
        ["createWebAppConfigImpl"],
        true,
        "./app-config.js",
      ),
      edge("barrel-app-config-generic", "barrel", "target", null, true, "./app-config.js"),
      edge(
        "barrel-app-config-inactive",
        "barrel",
        "target",
        ["createWebAppConfigImpl"],
        false,
        "./app-config.js",
      ),
      edge("barrel-suite", "barrel", "suite", ["createWebSuite"], true, "./suite.js"),
      edge("entry-barrel", "entry", "barrel", ["createWebSuite"], true, "./index.js"),
    ];
    const model = new InvestigationModel(build);

    const chain = model.exportImporterChain("target", "createWebAppConfigImpl");
    expect(
      chain?.steps.map((step) => ({
        edge: step.edge.id,
        depth: step.depth,
        importedExport: step.importedExport,
        importedBinding: {
          exportedName: step.importedBinding.exportedName,
          localName: step.importedBinding.localName,
        },
        importerExports: step.importerExports,
        importerBindings: step.importerBindings.map(({ exportedName, localName }) => ({
          exportedName,
          localName,
        })),
      })),
    ).toEqual([
      {
        edge: "suite-app-config",
        depth: 1,
        importedExport: "createWebAppConfigImpl",
        importedBinding: {
          exportedName: "createWebAppConfigImpl",
          localName: "createWebAppConfigImpl",
        },
        importerExports: ["createWebSuite"],
        importerBindings: [{ exportedName: "createWebSuite", localName: "createWebSuite" }],
      },
      {
        edge: "barrel-suite",
        depth: 2,
        importedExport: "createWebSuite",
        importedBinding: { exportedName: "createWebSuite", localName: "createWebSuite" },
        importerExports: ["createWebSuite"],
        importerBindings: [{ exportedName: "createWebSuite", localName: "createWebSuite" }],
      },
      {
        edge: "entry-barrel",
        depth: 3,
        importedExport: "createWebSuite",
        importedBinding: { exportedName: "createWebSuite", localName: "createWebSuite" },
        importerExports: [],
        importerBindings: [],
      },
    ]);
    expect(chain?.binding).toMatchObject({
      exportedName: "createWebAppConfigImpl",
      localName: "createWebAppConfigImpl",
    });
    expect(chain?.truncated).toBe(false);
  });

  it("continues only through the importer export that contains the imported binding use", () => {
    const base = manifest().modules.find((module) => module.id === "target") as BuildModule;
    const event: BuildModule = {
      ...base,
      id: "event",
      identifier: "/project/event.ts",
      name: "./event.ts",
      resource: "/project/event.ts",
      usedExports: ["messageRenderEvent"],
      providedExports: ["messageRenderEvent"],
    };
    const messageCount: BuildModule = {
      ...base,
      id: "message-count",
      identifier: "/project/message-count.ts",
      name: "./message-count.ts",
      resource: "/project/message-count.ts",
      usedExports: ["clearState", "setThreshold", "startWatch"],
      providedExports: ["clearState", "setThreshold", "startWatch"],
    };
    const consumer = (id: string): BuildModule => ({
      ...base,
      id,
      identifier: `/project/${id}.ts`,
      name: `./${id}.ts`,
      resource: `/project/${id}.ts`,
      entry: true,
      usedExports: true,
      providedExports: null,
    });
    const build = snapshot([]);
    build.manifest.modules = [
      event,
      messageCount,
      consumer("start-consumer"),
      consumer("clear-consumer"),
      consumer("threshold-consumer"),
    ];
    build.originalSources = new Map([
      ["event.ts", "export const messageRenderEvent = createEvent();"],
      [
        "message-count.ts",
        [
          'import { messageRenderEvent } from "./event";',
          "export const setThreshold = () => {};",
          "export const startWatch = () => {",
          '  messageRenderEvent.on("rendered", () => {});',
          "};",
          "export const clearState = () => {};",
        ].join("\n"),
      ],
    ]);
    build.references = [
      {
        id: "message-count-event",
        originId: "message-count",
        targetId: "event",
        dependencyType: "esm import specifier",
        request: "./event",
        exports: ["messageRenderEvent", "on"],
        active: true,
        location: null,
        sourcePath: "/project/message-count.ts",
        // Deliberately stale: carrier inference must follow the imported binding use.
        sourceLocation: {
          start: { line: 2, column: 0 },
          end: { line: 2, column: 10 },
        },
      },
      {
        id: "start-message-count",
        originId: "start-consumer",
        targetId: "message-count",
        dependencyType: "esm import specifier",
        request: "./message-count",
        exports: ["startWatch"],
        active: true,
        location: null,
      },
      {
        id: "clear-message-count",
        originId: "clear-consumer",
        targetId: "message-count",
        dependencyType: "esm import specifier",
        request: "./message-count",
        exports: ["clearState"],
        active: true,
        location: null,
      },
      {
        id: "threshold-message-count",
        originId: "threshold-consumer",
        targetId: "message-count",
        dependencyType: "esm import specifier",
        request: "./message-count",
        exports: ["setThreshold"],
        active: true,
        location: null,
      },
    ];

    const chain = new InvestigationModel(build).exportImporterChain("event", "messageRenderEvent");

    expect(
      chain?.steps.map((step) => ({
        edge: step.edge.id,
        importedExport: step.importedExport,
        importerExports: step.importerExports,
        precision: step.relationPrecision,
      })),
    ).toEqual([
      {
        edge: "message-count-event",
        importedExport: "messageRenderEvent",
        importerExports: ["startWatch"],
        precision: "exact",
      },
      {
        edge: "start-message-count",
        importedExport: "startWatch",
        importerExports: [],
        precision: "unavailable",
      },
    ]);
  });

  it("keeps default-export class names visible across importer hops", () => {
    const base = manifest().modules.find((module) => module.id === "target") as BuildModule;
    const foundation: BuildModule = {
      ...base,
      id: "foundation",
      identifier: "/project/foundation.js",
      name: "./foundation.js",
      resource: "/project/foundation.js",
      usedExports: ["default"],
      providedExports: ["default"],
    };
    const inner: BuildModule = {
      ...foundation,
      id: "inner",
      identifier: "/project/inner.js",
      name: "./inner.js",
      resource: "/project/inner.js",
    };
    const preview: BuildModule = {
      ...foundation,
      id: "preview",
      identifier: "/project/preview.js",
      name: "./preview.js",
      resource: "/project/preview.js",
    };
    const build = snapshot([]);
    build.manifest.modules = [foundation, inner, preview];
    build.originalSources = new Map([
      ["foundation.js", "export default class PreviewInnerFoundation {}"],
      [
        "inner.js",
        'import PreviewInnerFoundation from "./foundation.js"; export default class PreviewInner extends PreviewInnerFoundation {}',
      ],
      [
        "preview.js",
        'import PreviewInner from "./inner.js"; export default class Preview extends PreviewInner {}',
      ],
    ]);
    build.references = [
      {
        id: "inner-foundation",
        originId: "inner",
        targetId: "foundation",
        dependencyType: "esm import specifier",
        request: "./foundation.js",
        exports: ["default"],
        active: true,
        location: null,
      },
      {
        id: "preview-inner",
        originId: "preview",
        targetId: "inner",
        dependencyType: "esm import specifier",
        request: "./inner.js",
        exports: ["default"],
        active: true,
        location: null,
      },
    ];

    const chain = new InvestigationModel(build).exportImporterChain("foundation", "default");

    expect(chain?.binding).toMatchObject({
      exportedName: "default",
      localName: "PreviewInnerFoundation",
    });
    expect(
      chain?.steps.map((step) => ({
        parentId: step.parentId,
        imported: {
          exportedName: step.importedBinding.exportedName,
          localName: step.importedBinding.localName,
        },
        carriers: step.importerBindings.map(({ exportedName, localName }) => ({
          exportedName,
          localName,
        })),
      })),
    ).toEqual([
      {
        parentId: null,
        imported: { exportedName: "default", localName: "PreviewInnerFoundation" },
        carriers: [{ exportedName: "default", localName: "PreviewInner" }],
      },
      {
        parentId: "inner-foundation:default:1",
        imported: { exportedName: "default", localName: "PreviewInner" },
        carriers: [{ exportedName: "default", localName: "Preview" }],
      },
    ]);
  });

  it("uses native export ownership edges and stops module-execution terminals", () => {
    const consumer = source(
      "src/consumer.js",
      "consumer",
      "export const forwarded = value; export const alternate = value;",
    );
    const target = source("src/target.js", "target", "export const value = 1;");
    const entry = source(
      "src/entry.js",
      "entry",
      "import { forwarded } from './consumer.js'; console.log(forwarded);",
    );
    const build = snapshot([consumer, target, entry]);
    const consumerModule = build.manifest.modules.find((module) => module.id === "consumer");
    if (!consumerModule) throw new Error("Missing consumer module");
    consumerModule.entry = false;
    consumerModule.providedExports = ["forwarded", "alternate"];
    consumerModule.usedExports = ["forwarded", "alternate", "unrelated"];
    build.manifest.modules.push({
      id: "entry",
      identifier: "/project/src/entry.js",
      readableIdentifier: "./src/entry.js",
      name: "./src/entry.js",
      resource: "/project/src/entry.js",
      moduleType: "javascript/esm",
      chunks: [],
      issuer: null,
      entry: true,
      size: 20,
      usedExports: true,
      providedExports: ["unrelatedEntryExport"],
      optimizationBailout: [],
      nested: false,
    });
    build.manifest.capabilities.exportUsageGraph = "native";
    build.exportUsageEdges = [
      {
        id: "usage-forwarded",
        dependencyId: "dep-value",
        originModuleId: "consumer",
        originExport: ["forwarded"],
        targetModuleId: "target",
        targetExport: ["value", "field"],
        location: { start: { line: 1, column: 25 }, end: { line: 1, column: 30 } },
        sourcePath: "src/consumer.js",
        sourceLocation: {
          start: { line: 1, column: 25 },
          end: { line: 1, column: 30 },
        },
      },
      {
        id: "usage-alternate",
        dependencyId: "dep-value",
        originModuleId: "consumer",
        originExport: ["alternate"],
        targetModuleId: "target",
        targetExport: ["value", "field"],
        location: { start: { line: 1, column: 25 }, end: { line: 1, column: 30 } },
        sourcePath: "src/consumer.js",
        sourceLocation: {
          start: { line: 1, column: 25 },
          end: { line: 1, column: 30 },
        },
      },
      {
        id: "usage-entry",
        dependencyId: "dep-forwarded",
        originModuleId: "entry",
        originExport: null,
        targetModuleId: "consumer",
        targetExport: ["forwarded"],
        location: { start: { line: 1, column: 57 }, end: { line: 1, column: 66 } },
        sourcePath: "src/entry.js",
        sourceLocation: {
          start: { line: 1, column: 57 },
          end: { line: 1, column: 66 },
        },
      },
    ];
    const model = new InvestigationModel(build, report([consumer, target, entry]), new Map());

    const chain = model.exportImporterChain("target", "value");
    expect(chain).toMatchObject({ precision: "native", truncated: false });
    expect(chain?.steps).toHaveLength(2);
    expect(chain?.steps[0]).toMatchObject({
      importedExport: "value.field",
      importedBinding: { exportedName: "value.field", localName: "value.field" },
      importerExports: ["forwarded", "alternate"],
      relationPrecision: "exact",
      usageEdgeId: "usage-forwarded",
    });
    expect(chain?.steps[1]).toMatchObject({
      importedExport: "forwarded",
      importerExports: [],
      relationPrecision: "exact",
      usageEdgeId: "usage-entry",
    });
    expect(chain?.steps.some((step) => step.importerExports.includes("unrelated"))).toBe(false);
    expect(chain?.steps.some((step) => step.importerExports.includes("unrelatedEntryExport"))).toBe(
      false,
    );
    expect(model.snippet("usage-forwarded")).toMatchObject({
      kind: "usage",
      available: true,
      filename: "src/consumer.js",
      location: { start: { line: 1, column: 25 } },
    });
    expect(model.exportDeclaration("consumer", "forwarded")).toMatchObject({
      kind: "declaration",
      available: true,
      filename: "src/consumer.js",
      location: { start: { line: 1 } },
    });
  });

  it("fills native graph gaps for CommonJS usedExports true modules and keeps walking carriers", () => {
    const base = manifest().modules.find((item) => item.id === "target") as BuildModule;
    const module = (id: string, providedExports: string[] | null, entry = false): BuildModule => ({
      ...base,
      id,
      identifier: `/project/${id}.js`,
      readableIdentifier: `./${id}.js`,
      name: `./${id}.js`,
      resource: `/project/${id}.js`,
      moduleType: "javascript/auto",
      entry,
      usedExports: true,
      providedExports,
    });
    const normal = module("normal", ["normal"]);
    const tex = module("tex", ["TeXFont"]);
    const svg = module("svg", ["SVG"]);
    const entry = module("entry", null, true);
    const build = snapshot([]);
    build.manifest.modules = [normal, tex, svg, entry];
    build.manifest.capabilities.exportUsageGraph = "native";
    build.exportUsageEdges = [];
    build.originalSources = new Map([
      ["normal.js", "exports.normal = {};"],
      [
        "tex.js",
        [
          'var normal_js_1 = require("./normal.js");',
          "var TeXFont = (function () {",
          "  function TeXFont() {}",
          "  TeXFont.defaultChars = { normal: normal_js_1.normal };",
          "  return TeXFont;",
          "}());",
          "exports.TeXFont = TeXFont;",
        ].join("\n"),
      ],
      [
        "svg.js",
        [
          'var tex_js_1 = require("./tex.js");',
          "var SVG = (function () {",
          "  function SVG() { this.font = new tex_js_1.TeXFont(); }",
          "  return SVG;",
          "}());",
          "exports.SVG = SVG;",
        ].join("\n"),
      ],
      ["entry.js", 'import { SVG } from "./svg.js"; new SVG();'],
    ]);
    build.references = [
      {
        id: "tex-normal",
        originId: "tex",
        targetId: "normal",
        dependencyType: "cjs require",
        request: "./normal.js",
        exports: null,
        active: true,
        location: { start: { line: 1, column: 0 }, end: { line: 1, column: 44 } },
      },
      {
        id: "svg-tex",
        originId: "svg",
        targetId: "tex",
        dependencyType: "cjs require",
        request: "./tex.js",
        exports: null,
        active: true,
        location: { start: { line: 1, column: 0 }, end: { line: 1, column: 38 } },
      },
      {
        id: "entry-svg",
        originId: "entry",
        targetId: "svg",
        dependencyType: "esm import specifier",
        request: "./svg.js",
        exports: ["SVG"],
        active: true,
        location: { start: { line: 1, column: 9 }, end: { line: 1, column: 12 } },
      },
    ];
    const model = new InvestigationModel(build);

    const chain = model.exportImporterChain("normal", "normal");

    expect(chain).toMatchObject({ precision: "source-inferred", truncated: false });
    expect(
      chain?.steps.map((step) => ({
        edge: step.edge.id,
        importedExport: step.importedExport,
        importerExports: step.importerExports,
        precision: step.relationPrecision,
        line: step.edge.sourceLocation?.start.line,
      })),
    ).toEqual([
      {
        edge: expect.stringContaining("inferred-export-usage:tex-normal"),
        importedExport: "normal",
        importerExports: ["TeXFont"],
        precision: "exact",
        line: 4,
      },
      {
        edge: expect.stringContaining("inferred-export-usage:svg-tex"),
        importedExport: "TeXFont",
        importerExports: ["SVG"],
        precision: "exact",
        line: 3,
      },
      {
        edge: expect.stringContaining("inferred-export-usage:entry-svg"),
        importedExport: "SVG",
        importerExports: [],
        precision: "exact",
        line: 1,
      },
    ]);
    expect(model.snippet(chain?.steps[0]?.usageEdgeId ?? "")).toMatchObject({
      available: true,
      filename: "tex.js",
      location: { start: { line: 4, column: 35 } },
    });
  });

  it("propagates an unknown carrier as a bounded wildcard for usedExports true", () => {
    const base = manifest().modules.find((item) => item.id === "target") as BuildModule;
    const target: BuildModule = {
      ...base,
      id: "target",
      resource: "/project/target.js",
      usedExports: true,
      providedExports: ["value"],
    };
    const middle: BuildModule = {
      ...base,
      id: "middle",
      identifier: "/project/middle.js",
      name: "./middle.js",
      resource: "/project/middle.js",
      usedExports: true,
      providedExports: ["forwarded"],
    };
    const upstream: BuildModule = {
      ...middle,
      id: "upstream",
      identifier: "/project/upstream.js",
      name: "./upstream.js",
      resource: "/project/upstream.js",
      providedExports: ["wrap"],
    };
    const entry: BuildModule = {
      ...upstream,
      id: "entry",
      identifier: "/project/entry.js",
      name: "./entry.js",
      resource: "/project/entry.js",
      entry: true,
      providedExports: null,
    };
    const build = snapshot([]);
    build.manifest.modules = [target, middle, upstream, entry];
    build.manifest.capabilities.exportUsageGraph = "native";
    build.exportUsageEdges = [];
    build.originalSources = new Map([
      ["target.js", "exports.value = 1;"],
      [
        "upstream.js",
        'import { forwarded } from "./middle.js"; export const wrap = () => forwarded;',
      ],
      ["entry.js", 'import { wrap } from "./upstream.js"; wrap();'],
    ]);
    build.references = [
      {
        id: "middle-target",
        originId: "middle",
        targetId: "target",
        dependencyType: "cjs require",
        request: "./target.js",
        exports: null,
        active: true,
        location: null,
      },
      {
        id: "upstream-middle",
        originId: "upstream",
        targetId: "middle",
        dependencyType: "esm import specifier",
        request: "./middle.js",
        exports: ["forwarded"],
        active: true,
        location: null,
      },
      {
        id: "entry-upstream",
        originId: "entry",
        targetId: "upstream",
        dependencyType: "esm import specifier",
        request: "./upstream.js",
        exports: ["wrap"],
        active: true,
        location: null,
      },
    ];

    const chain = new InvestigationModel(build).exportImporterChain("target", "value");

    expect(chain?.steps.map((step) => step.importerExports)).toEqual([["*"], ["wrap"], []]);
    expect(chain?.steps[0]).toMatchObject({ relationPrecision: "conservative" });
    expect(chain?.steps[1]).toMatchObject({ importedExport: "*", relationPrecision: "exact" });
  });

  it("finds the dependency request when Rspack does not expose a usable location", () => {
    const consumer = source(
      "src/consumer.js",
      "consumer",
      'const before = 1;\nimport { value } from "./target.js";\nconsole.log(before, value);',
    );
    const target = source("src/target.js", "target", "export const value = 1;");
    const build = snapshot([consumer, target]);
    const edge = build.references[0];
    if (!edge) throw new Error("Missing reference fixture");
    edge.location = null;
    const model = new InvestigationModel(build, report([consumer, target]), new Map());

    const snippet = model.snippet("edge");
    expect(snippet).toMatchObject({
      available: true,
      filename: "src/consumer.js",
      location: {
        start: { line: 2 },
        end: { line: 2 },
      },
    });
    expect(snippet?.code?.content.slice(snippet.highlight?.start, snippet.highlight?.end)).toBe(
      "./target.js",
    );
  });

  it("opens the traced loader source instead of an arbitrary owner source", () => {
    const generated = source("src/consumer.js", "consumer", "generated consumer source");
    const transformed = source("outside/project/src/internal.ts", "consumer", "one line");
    const original = source("src/internal.ts", "consumer", "first\nxxxxxTARGETyyyy");
    const target = source("src/target.js", "target", "export const value = 1;");
    const build = snapshot([generated, transformed, original, target]);
    const edge = build.references[0];
    if (!edge) throw new Error("Missing reference fixture");
    edge.sourcePath = "/outside/project/src/internal.ts";
    edge.sourceLocation = {
      start: { line: 2, column: 5 },
      end: { line: 2, column: 11 },
    };
    const model = new InvestigationModel(
      build,
      report([generated, transformed, original, target]),
      new Map(),
    );

    const snippet = model.snippet("edge");
    expect(snippet).toMatchObject({
      available: true,
      filename: "src/internal.ts",
      location: edge.sourceLocation,
    });
    expect(snippet?.code?.content.slice(snippet.highlight?.start, snippet.highlight?.end)).toBe(
      "TARGET",
    );
  });

  it("prefers retained evidence when duplicate source identities have the same content", () => {
    const content = 'import { value } from "./target.js";';
    const duplicate = source("project/node_modules/pkg/consumer.js", "consumer", content);
    duplicate.metrics = metrics();
    const duplicateLine = duplicate.lines[0];
    if (!duplicateLine) throw new Error("Missing duplicate source line");
    duplicate.lines[0] = {
      ...duplicateLine,
      buildState: "not-emitted",
      runtimeState: "not-loaded",
      emittedBytes: 0,
      loadedBytes: 0,
      executedBytes: 0,
      ranges: [],
    };
    const retained = source("node_modules/pkg/consumer.js", "consumer", content);
    const retainedLine = retained.lines[0];
    if (!retainedLine) throw new Error("Missing retained source line");
    retained.lines[0] = {
      ...retainedLine,
      runtimeState: "not-loaded",
      loadedBytes: 0,
      executedBytes: 0,
      ranges: [],
    };
    const target = source("src/target.js", "target", "export const value = 1;");
    const build = snapshot([duplicate, retained, target]);
    build.manifest.context = "/project/packages/app";
    const edge = build.references[0];
    if (!edge) throw new Error("Missing reference fixture");
    edge.sourcePath = "/project/node_modules/pkg/consumer.js";
    const model = new InvestigationModel(build, report([duplicate, retained, target]), new Map());

    expect(model.snippet("edge")).toMatchObject({
      available: true,
      filename: "node_modules/pkg/consumer.js",
      highlight: { coverageStatus: "unloaded" },
      code: { sourceId: "node_modules/pkg/consumer.js" },
    });
  });
});
