import { describe, expect, it } from "vitest";
import { InvestigationModel } from "../../src/server/InvestigationModel.js";
import type {
  BuildManifest,
  BuildModule,
  BuildSnapshot,
  CoverageReport,
  SourceFileReport,
  UsageMetrics,
} from "../../src/shared/types.js";

function metrics(input: Partial<UsageMetrics> = {}): UsageMetrics {
  return {
    emittedBytes: 0,
    loadedBytes: 0,
    executedBytes: 0,
    unusedBytes: 0,
    notLoadedBytes: 0,
    mappedBytes: 0,
    unmappedBytes: 0,
    usageRatio: null,
    ...input,
  };
}

function manifest(): BuildManifest {
  return {
    hash: "build",
    mode: "production",
    context: "/project",
    publicPath: "/",
    builtAt: 1,
    assets: [],
    chunks: [],
    modules: [
      {
        id: "consumer",
        identifier: "/project/src/consumer.js",
        readableIdentifier: "./src/consumer.js",
        name: "./src/consumer.js",
        resource: "/project/src/consumer.js",
        moduleType: "javascript/auto",
        chunks: [],
        issuer: null,
        entry: true,
        size: 20,
        usedExports: true,
        providedExports: null,
        optimizationBailout: [],
        nested: false,
      },
      {
        id: "target",
        identifier: "/project/src/target.js",
        readableIdentifier: "./src/target.js",
        name: "./src/target.js",
        resource: "/project/src/target.js",
        moduleType: "javascript/auto",
        chunks: [],
        issuer: "./src/consumer.js",
        entry: false,
        size: 20,
        usedExports: ["value"],
        providedExports: ["value"],
        optimizationBailout: [],
        nested: false,
      },
    ],
    entrypoints: [],
    diagnostics: [],
    capabilities: {
      usedExports: "enabled",
      sourceMap: "full",
      originalLocations: "exact",
    },
    counts: {
      assets: 0,
      javascriptAssets: 0,
      chunks: 0,
      modules: 2,
      sourceMaps: 0,
      references: 1,
      codeGenerationSources: 1,
    },
    previewAvailable: false,
    publicPathSupported: true,
  };
}

function source(
  id: string,
  moduleId: string,
  content: string,
  state: "executed" | "not-executed" = "executed",
): SourceFileReport {
  return {
    id,
    path: id,
    displayPath: id,
    category: "first-party",
    metrics: metrics({
      emittedBytes: 10,
      loadedBytes: 10,
      executedBytes: state === "executed" ? 10 : 0,
      unusedBytes: state === "executed" ? 0 : 10,
      mappedBytes: 10,
      usageRatio: state === "executed" ? 1 : 0,
    }),
    chunks: [],
    loadedChunks: [],
    moduleIds: [moduleId],
    duplicated: false,
    content,
    lines: [
      {
        line: 1,
        text: content,
        buildState: "retained",
        runtimeState: state,
        emittedBytes: 10,
        loadedBytes: 10,
        executedBytes: state === "executed" ? 10 : 0,
        chunks: [],
        ranges: [{ startColumn: 0, endColumn: content.length, executed: state === "executed" }],
      },
    ],
  };
}

function report(files: SourceFileReport[]): CoverageReport {
  return {
    version: 2,
    buildHash: "build",
    createdAt: 1,
    metrics: metrics(),
    moduleMetrics: metrics(),
    importSummary: {
      importedEntries: 1,
      matchedAssets: 1,
      ignoredEntries: [],
      precision: "per-block",
    },
    tree: {
      id: "root",
      name: "Sources",
      path: "",
      kind: "root",
      category: "all",
      metrics: metrics(),
      chunks: [],
      duplicated: false,
      children: [],
    },
    files,
    chunks: [],
    opportunities: [],
  };
}

function snapshot(files: SourceFileReport[]): BuildSnapshot {
  return {
    manifest: manifest(),
    assets: new Map(),
    maps: new Map(),
    originalSources: new Map(
      files.flatMap((file) => (file.content ? [[file.path, file.content]] : [])),
    ),
    exportGraph: { modules: [], edges: [], sourceToModuleIds: {} },
    references: [
      {
        id: "edge",
        originId: "consumer",
        targetId: "target",
        dependencyType: "esm import",
        request: "./target.js",
        exports: ["value"],
        active: true,
        location: {
          start: { line: 1, column: 9 },
          end: { line: 1, column: 14 },
        },
      },
    ],
    codeGeneration: new Map([
      [
        "target",
        [
          {
            moduleId: "target",
            runtimes: [[]],
            content: "const value = 1;",
            map: null,
            mapError: "missing map",
          },
        ],
      ],
    ]),
    outputPath: "/project/dist",
    indexAsset: null,
  };
}

describe("InvestigationModel", () => {
  it("falls back to module code generation when mapped generated bytes are zero", () => {
    const target = source("src/target.js", "target", "export const value = 1;");
    target.metrics = metrics();
    const targetLine = target.lines[0];
    if (!targetLine) throw new Error("Missing target source line");
    target.lines[0] = {
      ...targetLine,
      buildState: "unknown",
      runtimeState: "not-loaded",
      emittedBytes: 0,
      executedBytes: 0,
      ranges: [],
    };
    const model = new InvestigationModel(snapshot([target]), report([target]), new Map());

    expect(model.module("target")?.views).toMatchObject({
      source: true,
      output: true,
      hasMappedOutput: false,
      preferred: "output",
      outputKind: "module-code-generation",
    });
    expect(model.code("target", "output", null)).toMatchObject({
      content: "const value = 1;",
      provenance: "module-code-generation",
      spans: [{ start: 0, end: 16, status: "unknown" }],
    });
  });

  it("paginates references, finds the shortest entry path, and returns covered usage code", () => {
    const consumer = source("src/consumer.js", "consumer", 'import { value } from "./target.js";');
    const target = source("src/target.js", "target", "export const value = 1;");
    const model = new InvestigationModel(
      snapshot([consumer, target]),
      report([consumer, target]),
      new Map(),
    );

    const references = model.references("target", "in", 0, 1);
    expect(references?.total).toBe(1);
    expect(references?.counts).toEqual({ in: 1, out: 0, both: 1 });
    expect(references?.entryPath.map((module) => module.id)).toEqual(["target", "consumer"]);
    const snippet = model.snippet("edge");
    expect(snippet).toMatchObject({
      available: true,
      filename: "src/consumer.js",
      highlight: { coverageStatus: "executed" },
      code: {
        content: 'import { value } from "./target.js";',
        spans: [{ status: "executed" }],
        hasPrevious: false,
        hasNext: false,
      },
    });
    expect(snippet?.code?.content.slice(snippet.highlight?.start, snippet.highlight?.end)).toBe(
      "value",
    );
  });

  it("walks importer export names through the bounded reference graph", () => {
    const target = {
      ...(manifest().modules.find((module) => module.id === "target") as BuildModule),
      name: "./app-config.js",
      resource: "/project/app-config.js",
      usedExports: ["createWebAppConfigImpl"],
      providedExports: ["createWebAppConfigImpl"],
    };
    const suite: BuildModule = {
      ...target,
      id: "suite",
      identifier: "/project/suite.js",
      name: "./suite.js",
      resource: "/project/suite.js",
      usedExports: ["createWebSuite"],
      providedExports: ["createWebSuite"],
    };
    const barrel: BuildModule = {
      ...suite,
      id: "barrel",
      identifier: "/project/index.js",
      name: "./index.js",
      resource: "/project/index.js",
    };
    const entry: BuildModule = {
      ...suite,
      id: "entry",
      identifier: "/project/entry.js",
      name: "./entry.js",
      resource: "/project/entry.js",
      entry: true,
      usedExports: true,
      providedExports: null,
    };
    const build = snapshot([]);
    build.manifest.modules = [target, suite, barrel, entry];
    const edge = (
      id: string,
      originId: string,
      targetId: string,
      exports: string[] | null,
      active = true,
      request = "./dependency.js",
    ) => ({
      id,
      originId,
      targetId,
      dependencyType: "esm import specifier",
      request,
      exports,
      active,
      location: null,
    });
    build.references = [
      edge("suite-app-config", "suite", "target", ["createWebAppConfigImpl"]),
      edge("barrel-app-config-generic", "barrel", "target", null, true, "./app-config.js"),
      edge(
        "barrel-app-config-inactive",
        "barrel",
        "target",
        ["createWebAppConfigImpl"],
        false,
        "./app-config.js",
      ),
      edge("barrel-suite", "barrel", "suite", ["createWebSuite"]),
      edge("entry-barrel", "entry", "barrel", ["createWebSuite"]),
    ];
    const model = new InvestigationModel(build);

    const chain = model.exportImporterChain("target", "createWebAppConfigImpl");
    expect(
      chain?.steps.map((step) => ({
        edge: step.edge.id,
        depth: step.depth,
        importedExport: step.importedExport,
        importerExports: step.importerExports,
      })),
    ).toEqual([
      {
        edge: "suite-app-config",
        depth: 1,
        importedExport: "createWebAppConfigImpl",
        importerExports: ["createWebSuite"],
      },
      {
        edge: "barrel-suite",
        depth: 2,
        importedExport: "createWebSuite",
        importerExports: ["createWebSuite"],
      },
      {
        edge: "entry-barrel",
        depth: 3,
        importedExport: "createWebSuite",
        importerExports: [],
      },
    ]);
    expect(chain?.truncated).toBe(false);
  });

  it("finds the dependency request when Rspack does not expose a usable location", () => {
    const consumer = source(
      "src/consumer.js",
      "consumer",
      'const before = 1;\nimport { value } from "./target.js";\nconsole.log(before, value);',
    );
    const target = source("src/target.js", "target", "export const value = 1;");
    const build = snapshot([consumer, target]);
    const edge = build.references[0];
    if (!edge) throw new Error("Missing reference fixture");
    edge.location = null;
    const model = new InvestigationModel(build, report([consumer, target]), new Map());

    const snippet = model.snippet("edge");
    expect(snippet).toMatchObject({
      available: true,
      filename: "src/consumer.js",
      location: {
        start: { line: 2 },
        end: { line: 2 },
      },
    });
    expect(snippet?.code?.content.slice(snippet.highlight?.start, snippet.highlight?.end)).toBe(
      "./target.js",
    );
  });

  it("opens the traced loader source instead of an arbitrary owner source", () => {
    const generated = source("src/consumer.js", "consumer", "generated consumer source");
    const transformed = source("outside/project/src/internal.ts", "consumer", "one line");
    const original = source("src/internal.ts", "consumer", "first\nxxxxxTARGETyyyy");
    const target = source("src/target.js", "target", "export const value = 1;");
    const build = snapshot([generated, transformed, original, target]);
    const edge = build.references[0];
    if (!edge) throw new Error("Missing reference fixture");
    edge.sourcePath = "/outside/project/src/internal.ts";
    edge.sourceLocation = {
      start: { line: 2, column: 5 },
      end: { line: 2, column: 11 },
    };
    const model = new InvestigationModel(
      build,
      report([generated, transformed, original, target]),
      new Map(),
    );

    const snippet = model.snippet("edge");
    expect(snippet).toMatchObject({
      available: true,
      filename: "src/internal.ts",
      location: edge.sourceLocation,
    });
    expect(snippet?.code?.content.slice(snippet.highlight?.start, snippet.highlight?.end)).toBe(
      "TARGET",
    );
  });

  it("prefers retained evidence when duplicate source identities have the same content", () => {
    const content = 'import { value } from "./target.js";';
    const duplicate = source("project/node_modules/pkg/consumer.js", "consumer", content);
    duplicate.metrics = metrics();
    const duplicateLine = duplicate.lines[0];
    if (!duplicateLine) throw new Error("Missing duplicate source line");
    duplicate.lines[0] = {
      ...duplicateLine,
      buildState: "not-emitted",
      runtimeState: "not-loaded",
      emittedBytes: 0,
      loadedBytes: 0,
      executedBytes: 0,
      ranges: [],
    };
    const retained = source("node_modules/pkg/consumer.js", "consumer", content);
    const retainedLine = retained.lines[0];
    if (!retainedLine) throw new Error("Missing retained source line");
    retained.lines[0] = {
      ...retainedLine,
      runtimeState: "not-loaded",
      loadedBytes: 0,
      executedBytes: 0,
      ranges: [],
    };
    const target = source("src/target.js", "target", "export const value = 1;");
    const build = snapshot([duplicate, retained, target]);
    build.manifest.context = "/project/packages/app";
    const edge = build.references[0];
    if (!edge) throw new Error("Missing reference fixture");
    edge.sourcePath = "/project/node_modules/pkg/consumer.js";
    const model = new InvestigationModel(build, report([duplicate, retained, target]), new Map());

    expect(model.snippet("edge")).toMatchObject({
      available: true,
      filename: "node_modules/pkg/consumer.js",
      highlight: { coverageStatus: "unloaded" },
      code: { sourceId: "node_modules/pkg/consumer.js" },
    });
  });
});
