import { describe, expect, it } from "vitest";
import { InvestigationModel } from "../../src/server/InvestigationModel.js";
import type {
  BuildManifest,
  BuildSnapshot,
  CoverageReport,
  SourceFileReport,
  UsageMetrics,
} from "../../src/shared/types.js";

function metrics(input: Partial<UsageMetrics> = {}): UsageMetrics {
  return {
    emittedBytes: 0,
    loadedBytes: 0,
    executedBytes: 0,
    unusedBytes: 0,
    notLoadedBytes: 0,
    mappedBytes: 0,
    unmappedBytes: 0,
    usageRatio: null,
    ...input,
  };
}

function manifest(): BuildManifest {
  return {
    hash: "build",
    mode: "production",
    context: "/project",
    publicPath: "/",
    builtAt: 1,
    assets: [],
    chunks: [],
    modules: [
      {
        id: "consumer",
        identifier: "/project/src/consumer.js",
        readableIdentifier: "./src/consumer.js",
        name: "./src/consumer.js",
        resource: "/project/src/consumer.js",
        chunks: [],
        issuer: null,
        entry: true,
        size: 20,
        usedExports: true,
        providedExports: null,
        nested: false,
      },
      {
        id: "target",
        identifier: "/project/src/target.js",
        readableIdentifier: "./src/target.js",
        name: "./src/target.js",
        resource: "/project/src/target.js",
        chunks: [],
        issuer: "./src/consumer.js",
        entry: false,
        size: 20,
        usedExports: ["value"],
        providedExports: ["value"],
        nested: false,
      },
    ],
    entrypoints: [],
    diagnostics: [],
    counts: {
      assets: 0,
      javascriptAssets: 0,
      chunks: 0,
      modules: 2,
      sourceMaps: 0,
      references: 1,
      codeGenerationSources: 1,
    },
    previewAvailable: false,
    publicPathSupported: true,
  };
}

function source(
  id: string,
  moduleId: string,
  content: string,
  state: "executed" | "not-executed" = "executed",
): SourceFileReport {
  return {
    id,
    path: id,
    displayPath: id,
    category: "first-party",
    metrics: metrics({
      emittedBytes: 10,
      loadedBytes: 10,
      executedBytes: state === "executed" ? 10 : 0,
      unusedBytes: state === "executed" ? 0 : 10,
      mappedBytes: 10,
      usageRatio: state === "executed" ? 1 : 0,
    }),
    chunks: [],
    loadedChunks: [],
    moduleIds: [moduleId],
    duplicated: false,
    content,
    lines: [
      {
        line: 1,
        text: content,
        buildState: "retained",
        runtimeState: state,
        emittedBytes: 10,
        executedBytes: state === "executed" ? 10 : 0,
        chunks: [],
        ranges: [{ startColumn: 0, endColumn: content.length, executed: state === "executed" }],
      },
    ],
  };
}

function report(files: SourceFileReport[]): CoverageReport {
  return {
    version: 1,
    buildHash: "build",
    createdAt: 1,
    metrics: metrics(),
    importSummary: {
      importedEntries: 1,
      matchedAssets: 1,
      ignoredEntries: [],
      precision: "per-block",
    },
    tree: {
      id: "root",
      name: "Sources",
      path: "",
      kind: "root",
      category: "all",
      metrics: metrics(),
      chunks: [],
      duplicated: false,
      children: [],
    },
    files,
    chunks: [],
    opportunities: [],
  };
}

function snapshot(files: SourceFileReport[]): BuildSnapshot {
  return {
    manifest: manifest(),
    assets: new Map(),
    maps: new Map(),
    originalSources: new Map(
      files.flatMap((file) => (file.content ? [[file.path, file.content]] : [])),
    ),
    references: [
      {
        id: "edge",
        originId: "consumer",
        targetId: "target",
        dependencyType: "esm import",
        request: "./target.js",
        exports: ["value"],
        active: true,
        location: {
          start: { line: 1, column: 9 },
          end: { line: 1, column: 14 },
        },
      },
    ],
    codeGeneration: new Map([
      [
        "target",
        [
          {
            moduleId: "target",
            runtimes: [[]],
            content: "const value = 1;",
            map: null,
            mapError: "missing map",
          },
        ],
      ],
    ]),
    outputPath: "/project/dist",
    indexAsset: null,
  };
}

describe("InvestigationModel", () => {
  it("falls back to module code generation when mapped generated bytes are zero", () => {
    const target = source("src/target.js", "target", "export const value = 1;");
    target.metrics = metrics();
    const targetLine = target.lines[0];
    if (!targetLine) throw new Error("Missing target source line");
    target.lines[0] = {
      ...targetLine,
      buildState: "unknown",
      runtimeState: "not-loaded",
      emittedBytes: 0,
      executedBytes: 0,
      ranges: [],
    };
    const model = new InvestigationModel(snapshot([target]), report([target]), new Map());

    expect(model.module("target")?.views).toMatchObject({
      source: true,
      output: true,
      hasMappedOutput: false,
      preferred: "output",
      outputKind: "module-code-generation",
    });
    expect(model.code("target", "output", null)).toMatchObject({
      content: "const value = 1;",
      provenance: "module-code-generation",
      spans: [{ start: 0, end: 16, status: "unknown" }],
    });
  });

  it("paginates references, finds the shortest entry path, and returns covered usage code", () => {
    const consumer = source("src/consumer.js", "consumer", 'import { value } from "./target.js";');
    const target = source("src/target.js", "target", "export const value = 1;");
    const model = new InvestigationModel(
      snapshot([consumer, target]),
      report([consumer, target]),
      new Map(),
    );

    const references = model.references("target", "in", 0, 1);
    expect(references?.total).toBe(1);
    expect(references?.entryPath.map((module) => module.id)).toEqual(["target", "consumer"]);
    expect(model.snippet("edge")).toMatchObject({
      available: true,
      filename: "src/consumer.js",
      highlight: { coverageStatus: "executed" },
    });
  });
});
